services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: clients 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: